### ISSUE TITLE
Crankshaft and Kodi

### ISSUE THREAD

**Issue by ketanpatil3** [opencardev/crankshaft#102]
Any way to integrate KODI and Crankshaft similar to the one described here.
[link](https://medium.com/@bendavey/bringing-android-auto-to-audi-navigation-plus-rns-e-using-a-raspberry-pi-3d7d3bd97d7a)

**Comment by htruong** [comment]
This feature will be considered as we resolve https://github.com/opencardev/crankshaft/issues/42

**Comment by hawkeyexp** [comment]
With upcoming builds based on crankshaft-ng branch system has a detection if you have kodi installed. If yes you get a button on main screen to launch kodi - also your kodi home folder is saved restored during system updates via usb stick. But note it is no official support and tested with kodi 17.6 installed from raspbian repo's.

**Comment by hawkeyexp** [comment]
Released with CS-NG

**Comment by Richard6360** [comment]
how to side load/install kodi on crankshaft ?
