### ISSUE TITLE
Random Dissertation in the crankshaft folder

### ISSUE THREAD

**Issue by tehniemer** [opencardev/crankshaft#108]
Not really an issue, but somehow a PDF made it into the crankshaft folder in ```boot```

Edit by Huan: Edited out the PDF name :)

**Comment by htruong** [comment]
That was very embarassing. I will re-create the image and delete the file.

**Comment by tehniemer** [comment]
Eh... Could have been worse, all it's done is confirm your smarty pants status 😜

**Comment by htruong** [comment]
Fixed!
