### ISSUE TITLE
Just turning off Pi

### ISSUE THREAD

**Issue by smartroad** [opencardev/crankshaft#110]
Is it a problem to just 'turn off' the Pi? I ask as I am having to run mine from the cigarette socket and that switches off with the car's ignition. The car is a lease one so I can't go playing around with the electrics as I would with if it were mine.

I know Linux likes to be shut down properly, but is it an issue to just turn off CS? If it is, is there any way to set the filesystem to read only when setup has been completed so turning off won't cause any issues? Is this stupid idea LOL

**Comment by tehniemer** [comment]
This is what I've been doing, hasn't been an issue.

**Comment by chunky74** [comment]
I think the worry is that you can brick/damage an area of your SD card.  Saying that - I'm powering up/down mine without any issue (yet - touch wood).  Take an image/copy of your working setup of the sd card and re-write to a new card if you damage it.

**Comment by metalmini** [comment]
https://uk.pi-supply.com/products/pi-ups-uninterrupted-power-supply-raspberry-pi

**Comment by metalmini** [comment]
For more inspiration: http://www.blackboxpi.com/

**Comment by hawkeyexp** [comment]
The system is designed to run in read only during normal operation. So a power off should not cause problems but it's more safe to release a clean shutdown.
