### ISSUE TITLE
Nothing is coming up on my display.

### ISSUE THREAD

**Issue by AshishGaur28** [opencardev/crankshaft#111]
I'm not even connecting any phone. I simply flashed the SD card with latest crackshaft but when I turn on the display, it only shows vertical black and white lines. And sometimes it keeps on going on and off continuously.
I tried with earlier version as well but that too doesn't seem to be working.

Is there something that I'm missing? I'm using official Raspi display.

P.S. I checked, my card is working fine. As i flashed it with regular raspbian and it booted up to desktop.

**Comment by AshishGaur28** [comment]
I can see the crankshaft screen through HDMI port but not through display port on raspi. This display port works fine with normal raspbian, as i mentioned earlier.

**Comment by htruong** [comment]
Please double-check your ribbon cable. The side that doesn't have the text should look like this:

![](https://camo.githubusercontent.com/5bd9265d0c824d245492d53a936dcce408d7b849/68747470733a2f2f63646e2e73686f706966792e636f6d2f732f66696c65732f312f303137362f333237342f66696c65732f617373656d626c79365f6c617267652e6a70673f3135333531343137353830363035303636323635)

Then, check the four additional jumper wires. You'll need to connect the 2 pins: Ground (GND/black) and 5V (red) to the 2 pins labelled GND and 5V of the touchscreen. Do not connect the two others you do not need it (but it doesn't do anything bad if you do so correctly).

Please let me know and give me a picture, so I can help you check.

**Comment by AshishGaur28** [comment]
I don't know what was the issue. After i checked with HDMI connection, I started to get the homescreen on the display as well. (I didn't change any connection) But still the homescreen comes up after a few auto-restarts only.

**Comment by Maju3** [comment]
Vertical lines on the display are depending on a bad contact.
Check the ribon cable,please.
