### ISSUE TITLE
Keyboard layout in Dev Mode defaults to UK and won't switch to anything else

### ISSUE THREAD

**Issue by tehniemer** [opencardev/crankshaft#115]
I'm having issues with the keyboard layout in dev mode. It is set to some UK layout and a couple of the keys are switched around or straight up missing. Specifically ```@``` and ```"``` are switched and ```#``` is nowhere to be found. I've tried setting it to a US standard, but it doesn't take.

**Comment by cydia2020** [comment]
Try `sudo dpkg-reconfigure keyboard-configuration`

**Comment by hawkeyexp** [comment]
Will add it to management tool in CS-NG for later builds so closing.
