### ISSUE TITLE
10.1" Touchscreen Not Working

### ISSUE THREAD

**Issue by iandunham2** [opencardev/crankshaft#118]
I'm trying to use Crankshaft using this touchscreen:

https://www.amazon.com/gp/product/B01H04GENA/ref=oh_aui_search_detailpage?ie=UTF8&psc=1

I can't get any touch response at all. I've run C.S. in Dev Mode, and have installed the eGalax drivers and have tried following this tutorial: https://github.com/opencardev/crankshaft/issues/64

But I can't get any response from the touchscreen.

C.S. definitely sees the touchscreen controller, when I run lsusb, it shows up as a USB object. There is just no response out of it.

Also, I tried installing Raspbian, and it recognizes the touchscreen right away.

**Comment by htruong** [comment]
Did you start OpenAuto in X11?

https://github.com/opencardev/crankshaft/wiki/Custom-touchscreens

**Comment by iandunham2** [comment]
Yes, I tried that. The screen and touch layer behave the same.

**Comment by KLVN** [comment]
~Any news? I'm currently struggling with mine, too.~
Nevermind, it works.
