### ISSUE TITLE
Notification sound doesn't stop playing

### ISSUE THREAD

**Issue by angrytomatoe** [opencardev/crankshaft#119]
Hi and thanks for all the work on crankshaft to make this possible!

I would like to share an issue with all of you. 
Whenever I connected my phone and Android Auto is started, the first incoming message triggers the notification sound. Then it won't stop playing the notification sound, it's just repeated over and over again... 
To stop it I have to restart the UI or reboot the device.

My setup:

- crankshaft release 0.2.4 2018-05-18 
- custom touchscreen 5" 
- Raspi Pi 3
- OnePlus 3T / LineageOS 14.1 / Android 7.1.2

**Comment by htruong** [comment]
This seems to be a problem with your cable to the phone. Have you tried a different, more solid cable, and a more reliable (enough amperage from a reputable brand) wall-plug to the Pi?
