### ISSUE TITLE
Query : Display size

### ISSUE THREAD

**Issue by amijoe2001** [opencardev/crankshaft#120]
I have a question about display size. Will this work for display size other than official RPi display? How does the cranskshaft application know the display size? or is it something done by aasdk?

**Comment by htruong** [comment]
Crankshaft/OA does not care about the display sizes. I have seen screens as big as 10 inches connected to a Pi and it works just fine!

**Comment by hawkeyexp** [comment]
With coming csng-pre8 a new scaling gui is included respecting real sceen size.
