### ISSUE TITLE
Feature Request: Music Auto Play on Phone Connect

### ISSUE THREAD

**Issue by t00fatt** [opencardev/crankshaft#124]
Would it be possible emulate a play/pause button press after a phone is connected so music will automatically start playing?

Is there anyway to check the phone connection state in a separate script without modifying the crankshaft build itself?

**Comment by nthanhtin** [comment]
Isn't it already implemented in Android?. In my case it automatically plays music when I plug my phone in and stops when I pull it out.

**Comment by Maju3** [comment]
Really?
In my case i need to click on the play button to start music playback.

**Comment by htruong** [comment]
Some player program such as Rocket Player (below) has the feature to automatically play upon connection. I think you can try out that feature.

![screenshot jun 23 2018 12_00_27 pm](https://user-images.githubusercontent.com/146489/41811417-4fac8784-76dd-11e8-9bac-211f5cafaa23.png)

**Comment by hawkeyexp** [comment]
A feature like auto play on connect could be nice but it should not be done by cs. There are solutions like players which can handle it or for example automation tools like tasker which can do the job for advanced users.
