### ISSUE TITLE
Output backend

### ISSUE THREAD

**Issue by Maju3** [opencardev/crankshaft#131]
On the crankshaft mainscreen in audio settings you can select between "rt audio" and "qt audio".
But which one is suggested to use?
What is the difference?

In my case i had audio crackles when i use rt audio.
But qt audio completelly solved all audio crackles.
BTW i use a USB dac.

**Comment by Maju3** [comment]
Well qt audio solves crackling sound for me.
So....no matter what the difference between qt audio or rt audio is :)

**Comment by htruong** [comment]
[RT audio](https://github.com/thestk/rtaudio) is a library that does things a bit differently compared to Qt Audio. If Qt Audio works for you, there is no reason yet to switch to RT Audio.
