### ISSUE TITLE
[csng] Kodi does not launch, stuck at login screen

### ISSUE THREAD

**Issue by dshokouhi** [opencardev/crankshaft#133]
- What phone do you have? What OS version? Pixel 2 XL 8.1 Crankshaft-NG Pre1 2018-07-01
- Steps to reproduce the bug, if you're planning to report a bug. Please indicate whether the bug is always repoducible.

1. Install latest crankshaft-ng
2. Login to dev mode and install kodi via `sudo apt-get install kodi`
3. launch `kodi`
4. Verify `/usr/bin/kodi` exists
5. Verify `/home/pi/.kodi` exists
6. Start crankshaft normally
7. Click on Kodi icon

User is stuck at login screen asking for password.

- Please provide any further information that you might find helpful.

**Comment by dshokouhi** [comment]
Also, I realize Kodi is not supported but thought I would mention this since it did not work for me.

Raspberry pi model 3b+ using 5" waveshare screen

**Comment by hawkeyexp** [comment]
let me have a look - last tested it was working...
ps: egl or x11 mode if csng ?

**Comment by dshokouhi** [comment]
Thanks for the quick reply! I believe egl as I never enabled x11 mode?

All I really did was follow these steps to install my touchscreen: https://waveshare.com/wiki/5inch_HDMI_LCD

**Comment by hawkeyexp** [comment]
ok i identified it - kodi tries to create it's home folder on /home/pi which is read only in normal mode so it can't be created. In dev mode you should be able to launch kodi. I will think about this behaviour later.

**Comment by hawkeyexp** [comment]
Solution done for pre2

**Comment by Richard6360** [comment]
is there a install script for kodi ?

**Comment by Richard6360** [comment]
how to login at dev mode ?

**Comment by pumpkintechlabs** [comment]
@Richard6360 no there isn't. You need to get into dev mode and install Kodi as per instructions in the original post (sudo apt-get install kodi). You also need to run crankshaft in X11 mode in order for Kodi to work.
