### ISSUE TITLE
[SOLVED] After entering DEV MODE, settings in crankshaft no longer save 

### ISSUE THREAD

**Issue by Hisma** [opencardev/crankshaft#134]
running latest version of crankshaft, if I ever enter dev mode for any reason, the moment I return to the normal crankshaft environment, I can no longer save any settings.  I can alter a setting, but the moment I hit "save" button, I am greeted with the "crankshaft" splashscreen, and the system hangs indefinitely until I pull power or reboot.  

Prior to entering DEV MODE, I am able to save crankshaft settings just fine.

**Comment by hawkeyexp** [comment]
running latest - csng pre1 ? - Please add [csng] in header for future issues to make it clear :-)
Which way you are rebooting ? via shell command or via gui ?

**Comment by Hisma** [comment]
hi hawkeye.  No I am not... I'm running the latest crankshaft version listed on getcrankshaft.com, dated May 18.

... However, I just visited the website however and saw you posted on update only a few hours ago.  I  will try "ng" and see if the issue still persists.  

Fortunately, my setup is very "turnkey", so it's easy for me to flash new versions.  The only custom item I have is the hifiberry digi module, which is very easy to integrate.  But I want to add more features soon like a backup cam that triggers upon reverse detection (via GPIO), so I tend to find myself in dev mode sometimes.  

I try to shutdown clean mostly, but if the system hangs, I have to pull power dirty.  Question - are there reports of SD card corruption by not having "graceful" shutdowns?  In my car it would be difficult to add this feature.

**Comment by hawkeyexp** [comment]
Hi Hisma, yes give csng a try - safing settings should work without probs there.
In the csng you have a management tool called `crankshaft` to also setup your hifiberry (i have one, too).
for example `crankshaft audio hifiberry dacplus` setup's mine. Type `crankshaft` in shell to list options and supported modules.

Instant power off should be usually no prob cause system is designed to be read only in normal mode to prevent from this problems - but as you no - nothing is 100% safe.

**Comment by Hisma** [comment]
you can close this, I confirmed this works now.  

Also, using`crankshaft audio hifiberry digi` also worked for me as well to configure my sound.  Nice and easy :).  Good work so far!

**Comment by hawkeyexp** [comment]
Thx for feedback :-)

"Nice and easy :)" -> that was the idea why a management tool was created :-)
