### ISSUE TITLE
[csng] Screen/Pi shutdown timings

### ISSUE THREAD

**Issue by Maju3** [opencardev/crankshaft#136]
Hi.
Is it possible to add the timing settings for screen off and pi shutdown after disconnecting phone to the main screen settings?
Maybe you could include a settings tab "system" next to the settings tabs "audio","video" ?

**Comment by hawkeyexp** [comment]
Good idea but complexer thing possible later

**Comment by hawkeyexp** [comment]
Init done for pre2 - will be extended with next releases.
