### ISSUE TITLE
General system settings on mainscreen

### ISSUE THREAD

**Issue by Maju3** [opencardev/crankshaft#141]
Just as suggestion.
What do you think about general system settings on mainscreen?
I mean like kodi or volumino do.
This way you have a gui where you can do settings for audio hardware like selecting which dac you use.
Or which audiooutput you use (3.5 jack or usb).
Or for the screen/pi shutdown timings like i suggested in an other post.
I just think that some gui for general settings makes it MUCH easier to config CS especially for people WITHOUT linux knowledge.

**Comment by tehniemer** [comment]
This is a great idea, I would love to see this implemented.

**Comment by hawkeyexp** [comment]
Thinking about some ways to release something - currently i'm extending the settings menu by a crankshaft page :-) So stay tuned...

**Comment by Maju3** [comment]
Sounds good to me!
Thank you!

**Comment by hawkeyexp** [comment]
Initial steps done in settings menu. It will be extended step by step.
