### ISSUE TITLE
[csng] Rotating screen does not work.

### ISSUE THREAD

**Issue by dinapappor** [opencardev/crankshaft#143]
Shorting pins 40 and 39 does not work (using a jumper). Adding lcd_rotate=2 to config.txt works briefly and then flips the image upside down again, like 5 or 10 seconds after boot.

I am using RPI 3B+ and official touch screen.

**Comment by hawkeyexp** [comment]
Which Crankshaft version ? NG or Classic ?

**Comment by dinapappor** [comment]
The latest one `Crankshaft OpenCarOS NG Pre1 2018-07-01`. Setting `FLIP_SCREEN=1` and adding `lcd_rotate=2` manually did seem to do the trick. Let me know if you need me to do any testing on my end.

**Comment by hawkeyexp** [comment]
I have checked the gpio trigger and it works fine.
You do not need to set it in config.txt - during boot a service checks if it is set in crankshaft_env.sh or triggered by gpio and if yes it will setup the config.txt.
You can also check if system recognizes your gpio input with this commands:

`crankshaft gpio status` = shows your configured gpio's status
`crankshaft gpio all` = shows all gpio's status

Is the global ENABLE_GPIO enabled (set to 1) ? - if not 1 no gpio actions will be used.
PS: Make sure your gpio trigger stays closed to be set - the service checks it on every boot to revert flip if no longer needed.

**Comment by hawkeyexp** [comment]
Closing - no feedback
