### ISSUE TITLE
General System settings on mainscreen

### ISSUE THREAD

**Issue by htruong** [opencardev/crankshaft#144]
Filed for @maju3. I have moved this issue to the issue tracker from the Wiki.

Just as suggestion. What do you think about general system settings on mainscreen. I mean like audio hardware settings if you want to use a hifiberry dac or allo boss dac or just a usb dac. Or for the shutdown pi timings like suggested in my other post.

What i mean is to have this settings in a gui like kodi or volumino do. That makes it MUCH easier to config for people WITHOUT linux knowledge you know. Sure this means much work but i think it could be worth it.

**Comment by Maju3** [comment]
Double post,sorry !

**Comment by Maju3** [comment]
This "issue" can be closed.

**Comment by htruong** [comment]
Close issue per @Maju3's suggestion
