### ISSUE TITLE
[Q] Headunit-wireless

### ISSUE THREAD

**Issue by Luard** [opencardev/crankshaft#147]
First of all, nice work in this project!

Now, my question is about headunit-wireless: Is it possible to run Android Auto and connect with my mobile in wireless mode? I've seen that the new version includes some new features but I'm not able to connect my Xiaomi through WiFi. I used my mobile device as a server in Android auto app but no way :/

Kind regards.

**Comment by hawkeyexp** [comment]
Hi,
generally openauto can support wifi clients ( i have never tested and no compatible device).
Caused by some reasons wifi connection is not supported in the Classic version and in the NG.
Possible on a later time we will re-think about it.
