### ISSUE TITLE
[csng] No audio

### ISSUE THREAD

**Issue by smartroad** [opencardev/crankshaft#149]
- What phone do you have? What OS version?
Nokia 8, Android 8.1, Pi2, Official Screen

- Steps to reproduce the bug, if you're planning to report a bug. Please indicate whether the bug is always repoducible.
Plug in and use - sometimes sound is not produced using the internal jack of the Pi. Intermittent, doesn't happen every time.

- Please provide any further information that you might find helpful.
Have noticed that when the audio doesn't start the touch panel has stopped working as well, could be a coincidence or related to #150

**Comment by Maju3** [comment]
In my case solved with csng pre2

**Comment by smartroad** [comment]
Solved for me with NG2 😸
