### ISSUE TITLE
[csng] Touch screen unresponsive

### ISSUE THREAD

**Issue by smartroad** [opencardev/crankshaft#150]
What phone do you have? What OS version?
Nokia 8, Android 8.1, Pi2, Official Screen

- Steps to reproduce the bug, if you're planning to report a bug. Please indicate whether the bug is always repoducible.
Sometimes the system will not respond to touch inputs

- Please provide any further information that you might find helpful.
When this happens I have been able to set Waze to start navigating but then the touch becomes unresponsive. I only noticed first time as I was unable to move the map around. I also noticed that at the same time the sound stops working, so could be related to #149 or just a coincidence.

**Comment by hawkeyexp** [comment]
Possible a bug is found - have to been tested again if still present in upcoming Pre2

**Comment by smartroad** [comment]
Great will test once out :)

**Comment by smartroad** [comment]
As an extra note, discovered it stops responding when the phone is connected before crankshaft has loaded/booted

**Comment by Maju3** [comment]
In my case solved with csng pre2

**Comment by smartroad** [comment]
Solved with ng pre2 here as well 😁

**Comment by hawkeyexp** [comment]
perfect
