### ISSUE TITLE
[csng] Access settings from AA

### ISSUE THREAD

**Issue by smartroad** [opencardev/crankshaft#152]
On the 'other apps' page (far right button on AA) there is a listing for "Return to OpenAuto". At the moment if you press it it presents a blank screen. Is there anyway of taking you back to the settings screen, like when you have no phone attached?

The only car I drove which had AA had the same option and it returned you to the cars UI. Would be useful for switching day/night modes or adjusting brightness if you got the wrong level without having to unplug your phone.

**Comment by hawkeyexp** [comment]
same base idea like #151
