### ISSUE TITLE
[csng] trigger day/night mode via GPIO

### ISSUE THREAD

**Issue by Hisma** [opencardev/crankshaft#162]
This is just a feature request, and perhaps it already exists, but I would like to see a GPIO trigger for day/night mode.  Currently it's a feature of the rtc, but I would rather just tie the day/night mode to my car's illumination wire.  That way, night mode is triggered when I turn on my car headlights.  It's better this way as sometimes it's dark during daytime (dark storm clouds, passing through tunnel etc).  That is the way the majority of stock HUs handle day/night mode as well.  

thanks!

**Comment by Maju3** [comment]
Good idea!

**Comment by Maju3** [comment]
@hawkeyexp 
I have sent you an email to hawkeeyexp@gmail.com
;)

**Comment by hawkeyexp** [comment]
@Maju3 typo in address ;-) ee -> e

**Comment by pigr8** [comment]
i would like this too :)

**Comment by hawkeyexp** [comment]
Will be released later if a way is found to trigger also aa if day/night is switching. Currently aa uses the state which is selected on connecting a device.

**Comment by t00fatt** [comment]
@hawkeyexp does that mean even with an RTC the day/night state only changes when connecting a device? Or will the day/night status change while a device is connected and the time changes from day to night or vice versa?

**Comment by hawkeyexp** [comment]
with an rtc the gui will switch time based between day and night. The state of the gui in the moment you connect your phone will set the day/night mode of android auto. The android auto gui will currently not switch while phone is connected and the system in background switches from day to night or back.

**Comment by t00fatt** [comment]
I see. Can a feature be added that without an RTC, a GPIO pin can be read to set the day/night state before a device is connected? I am already controlling the screen brightness with a GPIO pin, but would like day/night setting to be automatically set before a device is connected.

EDIT: would it at least be possible to change the day/night state through the crankshaft manager?

**Comment by hawkeyexp** [comment]
With upcoming release csmt can switch day/night and you can add custom script to control via gpio.

`crankshaft mode day|night`
