### ISSUE TITLE
[csng] Custom screen resolution

### ISSUE THREAD

**Issue by rubenverhoef** [opencardev/crankshaft#165]
I have a 7" waveshare type C 1024 x 600 screen. It works but the crankshaft homescreen is not full size and when i press out of the picture at the black parts i get a black cross.

Also in android auto the touches in the 800x480 area are working but the rest is not responding. The android auto display is displaying over the whole screen.

**Comment by Maju3** [comment]
Edit config.txt file.
On windows use notepad++

Add this to config.txt

hdmi_group=2
hdmi_mode=87
hdmi_cvt 1024 600 60 3 0 0 0
hdmi_force_hotplug=1

**Comment by rubenverhoef** [comment]
Sorry I forgot to mention, I have set the config file with this:
`
hdmi_group=2
hdmi_mode=87
hdmi_cvt 1024 600 60 6 0 0 0
hdmi_drive=1
`

Almost everything is full screen but not the home screen. The clock is not at the upper right and the default wallpaper is not full screen.
Touches out of the wallpaper "box" will result in a black cross.
Android auto interface is full screen but touches outside the 800x480 "box" don't do anything to the Android auto interface. Inside the 800x480 it works correctly.

**Comment by rubenverhoef** [comment]
I'm seeing some hard coded 800x480 screen resolution in the openauto code. I think we need to adjust these values acording to the screen resolution. I'm also seeing hard coded button positions (x,y) so we need to make that also depending on the screen resolution.

**Comment by hawkeyexp** [comment]
we will later have a look on it

**Comment by hawkeyexp** [comment]
New gui is work in progress which also addresses scaling gui.

**Comment by hawkeyexp** [comment]
Feature ready for next release.

**Comment by sastreae** [comment]
hello. Do you have images of the project with widescreen? how energizing that screen? so far i have the official screen of element14

**Comment by AndreySV** [comment]
Could it be any resolution including widescreen support? How can it be configured?

**Comment by matt2005** [comment]
Can you try the new refactored alpha release? I'm pretty sure it already handles this.
