### ISSUE TITLE
stereo sound for system-level audio?

### ISSUE THREAD

**Issue by Hisma** [opencardev/crankshaft#169]
feature-request.  The sound quality for navigation, voice control, etc, is all mono and is noticeably of lower quality than music.  I'm not sure if this is something that is inherently part of the design of AA/OpenAuto, but if possible, it would be nice if system sounds could be routed the same way music is.  

This would also help with volumes not matching.  In my case, system volume tends to be a bit lower than music.

**Comment by hawkeyexp** [comment]
Issue should be placed @ openauto by f1x caus it's audio handling of the core app.
