### ISSUE TITLE
Continuous integration build

### ISSUE THREAD

**Issue by htruong** [opencardev/crankshaft#17]
It would be nice to eventually be able to have an automated build system in Docker or any continuous integration system. There are more scripting needed before that becomes a reality.

**Comment by htruong** [comment]
I'm bumping this to the nearest alpha release. Having a reproducible environment means that more people will be able to assist with developing Crankshaft, thus justitifies the prioritization of the ticket.

I hope to not having to be the sole person who can produce the whole image. This will certainly help with times when I'm busy working on my personal work and life.

**Comment by htruong** [comment]
Building in an emulated environment messes up some assumptions about the capabilities of the CPU, resulting in janky performance. This idea is now pivoted to building on an RPi 0 raspbian-lite continuous integration environment.

**Comment by htruong** [comment]
0.2.1 provides a script to build Qt5 on raspbian. We will need to think about how we want to build openauto and aadsk because they will change in the future.

**Comment by Almagnus1** [comment]
Have you considered using cmake to generate a build?

**Comment by htruong** [comment]
I am working on buildroot-based builds. This is going to be somewhat in the long run.

**Comment by matt2005** [comment]
Setup and working
