### ISSUE TITLE
Run Kodi at first, no Touch.

### ISSUE THREAD

**Issue by schuest** [opencardev/crankshaft#171]
Hello, thanks for your great project.

What i'm doing is:

in startup.sh i run ./kodi (installed via apt-get).
At my Kodi Skin i got a Magic Button who runs a script.
This Script starts /usr/local/bin/autoapp.

Everything looks good but i can't touch the buttons in Crankshaft, it looks like kodi take over the input of the screen.

If i do the other way and push the Kodi button who appears in crankshaft then it works.

How did you run Kodi? At the log i see
> [OpenAuto] [CS] Run kodi binary.

I know Kodi is not supported but i only want to know how you implemented the Kodi start in CS.

I'm Using the 2018-07-13-crankshaft-ng-9B0FBA9 image.
I got a RPI3b+ with the original 7" touchscreen display.

**Comment by cydia2020** [comment]
Hmmm. My Kodi isn't even launching, it just crashes after clicking on the icon

**Comment by hawkeyexp** [comment]
Just some short notes:

`in startup.sh i run ./kodi (installed via apt-get).
At my Kodi Skin i got a Magic Button who runs a script.
This Script starts /usr/local/bin/autoapp.` - Don't do it this way!

- openauto will show a button if kodi is detected to be installed via the official repo.
- kodi isn't official supported.
- kodi needs a home folder - cs works as read only so it can't be created. The solution is a external storage stick for example. The partition must be named CSSTORAGE. If it is detected during boot it will be mounted as perma storage and the kodi folder will be redirected to it :-)
Also this storage solution is used for the dashcam mode if the rpi cam is used.

**Comment by pumpkintechlabs** [comment]
@hawkeyexp could you please elaborate on how to create a partition named CSSTORAGE on USB drive?

**Comment by hawkeyexp** [comment]
It is the label of the drive - on windows just rename the drive.
On linux you have multiple ways to rename via gui or via shell command.

**Comment by pumpkintechlabs** [comment]
Thanks! I got that working. Renamed the USB drive in windows and Kodi works now. Had troubles with the sound being distorted when Kodi plays anything - fixed it with 

`audio_pwm_mode=2` in /boot/config.txt

All is good apart from the fact that the USB drive does not like hard shutdown and corrupts every time. I do not run any relays or shutdown scripts - Pi just looses power as soon as i turn the car off. Might have to go with relay option...

**Comment by hawkeyexp** [comment]
Yes that can happen cause the csstorage must be rw - all other is ro.
Does it fix the corruption during boot ?

**Comment by pumpkintechlabs** [comment]
@hawkeyexp No it doesn't appear to recover after the USB has been corrupted. The sequence of events is as follows:

Open Kodi,
Play a media file,
Hard reboot (power off then on)
Kodi doesnt launch anymore - crashes after on startup (USB is corrupted). 

If i reformat USB drive - it work fine.

I haven't tried soft reboot from CS menu though.

**Comment by hawkeyexp** [comment]
I have done a rework for handling csstorage to be more agressiv and failsave. Should be fixed on pre4.

**Comment by pumpkintechlabs** [comment]
@hawkeyexp Oh wow thanks a lot! Will save me pulling the dash apart and re-wiring it! When is pre4 due to drop?

**Comment by hawkeyexp** [comment]
pre4 will be available on sunday for public friday for patreon users

**Comment by pumpkintechlabs** [comment]
@hawkeyexp if you would like me to test it before public release on Sunday, PM me with the link to the image when it's available. I'd be happy to help out.

**Comment by pumpkintechlabs** [comment]
@hawkeyexp Did pre4 release get pushed back?

**Comment by hawkeyexp** [comment]
There was a bug to fix so i skipped the release this weekend. Feel free to contact me hangouts for more informations.
