### ISSUE TITLE
[CSNG] Shutdown_Button service hangs system on boot

### ISSUE THREAD

**Issue by Fotchman** [opencardev/crankshaft#174]
Not sure if this is a CSNG issue or something else.
On a clean install of 2018-07-13-crankshaft-ng-9B0FBA9 after installing the "reboot/shutdown script from github https://github.com/scruss/shutdown_button, the system hangs on the splash screen during boot. Most times a power off and back on will let the system boot through (but not always), and randomly the system will hang at the CLI prompt. Buttons never do work, sometimes also locking the system. Disabling the service and rebooting/halting from CLI works every time. Tried an alternate GPIO with the same results. I'm no expert, but I was able to recreate this multiple times on multiple clean installs. All tests while in Dev mode.

Installed hardware:
PI3
Galaxy S9+ 
HiFiBerry
Official 7" screen

**Comment by Maju3** [comment]
Have you tested the script with crankshaft versions before crankshaftNG ?

**Comment by Fotchman** [comment]
Maju3 - just booted the latest release of master CS and the shutdown and reboot timers work each time. No hangs or other issues. Will reload previous versions of CSNG to see if/when the feature breaks.

**Comment by hawkeyexp** [comment]
The pre4 this weekend is on its way and includes a gpio based shutdown option with cunfigurable delay time. Try out if it is usefull for you and if solved close the issue please.

**Comment by Fotchman** [comment]
Thank - will check it out and let you know.
Thanks for everything,

**Comment by hawkeyexp** [comment]
You're welcome
