### ISSUE TITLE
[csng][Feature Request] Disabling screen and shutdown timers

### ISSUE THREAD

**Issue by pumpkintechlabs** [opencardev/crankshaft#175]
Hi there,

Firstly let me thank everyone for their hard work on this awesome project!

With the addition of the extended settings and the timer adjustments - could we please have an option to disable screen and shutdown timers? For example if we set any of those timers to 0 (zero) it will disable them.

Thanks

**Comment by hawkeyexp** [comment]
will be included for next build

**Comment by hawkeyexp** [comment]
I will close the issue cause it's tested an working for upcoming pre4.
