### ISSUE TITLE
Audio settings are not saved

### ISSUE THREAD

**Issue by andreacampanella** [opencardev/crankshaft#183]
I "un-tick' the Audio settings , and then I press save , it return to the main screen , I connect my phone , everything is fine , the audio is routed (as , not routed ) as I want , but if I restart the raspberry pi , the settings are lost , everything single time I have to in select the audio settings and then save , it never saves them.

**Comment by hawkeyexp** [comment]
You have to add info's about version etc - in this style nobody can hell you!

**Comment by cydia2020** [comment]
Same here, alsamixer settings were not saved, real pain in the back.

**Comment by andreacampanella** [comment]
Yes , sorry , I'm using crankshaft-ng pre 4

**Comment by hawkeyexp** [comment]
No pre4 is out - it's work in progress so opening issues makes no sense - sorry.
Issues must be based on published releases.

**Comment by andreacampanella** [comment]
So, you are not collecting bugs for your dev release? how you are going to find bugs? guessing?

**Comment by hawkeyexp** [comment]
Not in this way...
- no information about something in initial post
- talking about a pre4 which was never released and is cunfusing other users
