### ISSUE TITLE
[CSNG] Custom Buttons

### ISSUE THREAD

**Issue by glennsaint** [opencardev/crankshaft#186]
Hi, is it possible to add a button and/or modify the appearance of the CS Buttons? I am using pre3. thanks!

**Comment by hawkeyexp** [comment]
On a later time i will have a deeper look on it what is possible - ideas are present but not ready.

**Comment by petterhj** [comment]
Does QT somehow allow loading the UI-files (e.g. autoapp/UI/mainwindow.ui) and/or resource files at boot time? This could possibly at least allow users to add (graphics, static text) and reposition/hide existing elements as well as "skin" the user interface in general.

**Comment by hawkeyexp** [comment]
It seems there is a class for this case of use: http://doc.qt.io/qt-5/quiloader.html but nothing included currently.

**Comment by hawkeyexp** [comment]
New gui is work in progress which also addresses scaling gui and custom buttons.

**Comment by hawkeyexp** [comment]
Feature ready for next release.
