### ISSUE TITLE
Stuck in the devmode of Crankshaft

### ISSUE THREAD

**Issue by Paliscool** [opencardev/crankshaft#188]
Hello, this is my issue

Image version of Crankshaft used: 2018-07-13-crankshaft-ng-9B0FBA9

I have a Kuman screen 5''. And the touch screen worked (on Raspbian Os) only if we install the driver. So in order to do that I activate the devmode and I execute the same script I use on Raspbian for installing the driver

The script in question: 

```
#!/bin/bash
sudo cp -rf ./boot/config-5.txt /boot/config.txt 
sudo cp ./usr/cmdline.txt /boot/
sudo cp ./usr/inittab /etc/
sudo cp -rf ./usr/99-fbturbo.conf-HDMI /usr/share/X11/xorg.conf.d/99-fbturbo.conf 
sudo mkdir /etc/X11/xorg.conf.d 
sudo cp -rf ./usr/99-calibration.conf-5 /etc/X11/xorg.conf.d/99-calibration.conf 
nodeplatform=`uname -n`
kernel=`uname -r`
version=`uname -v`
if test "$nodeplatform" = "raspberrypi";then
echo "this is raspberrypi kernel"
version=${version%% *}
version=${version#*#}
echo $version
if test $version -lt 970;then
echo "reboot"
else
echo "need to update touch configuration"
sudo dpkg -i -B xserver-xorg-input-evdev_1%3a2.10.3-1_armhf.deb
sudo cp -rf /usr/share/X11/xorg.conf.d/10-evdev.conf /usr/share/X11/xorg.conf.d/45-evdev.conf
echo "reboot"
fi
else
echo "this is not raspberrypi kernel, no need to update touch configure, reboot"
fi
sudo reboot
```

The script executes himself without any issue. The driver seems to have been installed successfully so I change back in crankshaft/crankshaft_env.sh DEV_MODE=1 to DEV_MODE=0.

But when I reboot crankshaft return back to devmode even though in crankshaft_env.sh we can see that DEV_MODE=0 is still there.

The modification of config.txt
```
dtparam=audio=on
max_usb_current=1
hdmi_group=2
hdmi_mode=1
hdmi_mode=87
hdmi_drive=1
hdmi_cvt 800 480 60 6 0 0 0
dtoverlay=ads7846,cs=1,penirq=25,penirq_pull=2,speed=50000,keep_vref_on=0,swapxy=0,pmax=255,xohms=150,xmin=200,xmax=3900,ymin=200,ymax=3900
```

The modification of cmdline.txt

```
dwc_otg.lpm_enable=0 console=tty1 console=ttyAMA0,115200 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait fbcon=map:10 fbcon=font:ProFont6x11 logo.nologo
```

Thanks !

**Comment by hawkeyexp** [comment]
I only can say don't use installer scripts - they usually are ugly written and do a copy over of files which can break something in customized systems. You have to manually check each mod the script will exec and do it manually without breaking current config.
Please move to reddit for helping configure your custom screen - it's not a cs fault in this case.
