### ISSUE TITLE
Unable to exit Dev mode after screen driver install

### ISSUE THREAD

**Issue by Palisflying** [opencardev/crankshaft#189]
Hello, 
My crankshaft is working smoothly on my Raspberry 3B+ with Kuman 5" display and the latest version of crankshaft NG, except the touchscreen function. 
After installing crankshaft i use the Dev mode to install kuman official touchscreen driver but after this I am unable to exit the Dev mode. In the config file the devmode=0 but the raspberry do not start crankshaft and restart always in Dev mode. I have done twice the install and always the same behavior. I have checked the touchscreen when I install the official Kuman driver with raspbian and without crankshaft and it is working well. :/
I have tried the X11 mode but no effect...
Any ideas?

**Comment by hawkeyexp** [comment]
Have a look here:
https://github.com/opencardev/crankshaft/issues/188
