### ISSUE TITLE
[CSNG] Feature Request: Add cam_overlay (usb camera player, /dev/video0)

### ISSUE THREAD

**Issue by maskaz** [opencardev/crankshaft#191]
I have found project for usb camera player that overlays AA.
Link: https://github.com/meekys/cam_overlay
I have added it to my AA project and it works like a charm and I would like to ask you to add it to default Crankshaft compilation.
For configure: helping lines texture can be removed by change png picture to blank.

**Comment by hawkeyexp** [comment]
We decided to only support out of the box the rpi cam module.
Sorry.

**Comment by hawkeyexp** [comment]
time has changed - with alpha-3 builtin.

**Comment by Yokosa** [comment]
how to make the camera_overlay overlay the camera image?

**Comment by Yokosa** [comment]
how to make the camera_overlay overlay the camera image?
