### ISSUE TITLE
Issues With Fe-Pi Soundcard

### ISSUE THREAD

**Issue by noahajac** [opencardev/crankshaft#196]
- What phone do you have?
Android One Moto X4

- What OS version?
Android 8.1.0

- What crankshaft version?
Crankshaft OpenCarOS NG Pre4 2018-08-03

- Steps to reproduce the bug, if you're planning to report a bug. Please indicate whether the bug is always repoducible.
Mic input just doesn't work. For the debug file, I have done the following:
1. Went into settings and attempted to set the volume for input to 100.
2. Connected phone
3. Triggered "Okay Google" prompt and attempted to say things but with no response.
4. Disconnected phone

- Starting with pre4: Boot into dev mode (can be selected in settings).
  Reproduce the possible bug. Create the debug logs by pushing the grey button on bottom of screen.
  Add the created file (/boot/debug.zip) to the issue.
[debug.zip](https://github.com/opencardev/crankshaft/files/2275438/debug.zip)

- Please provide any further information that you might find helpful if available.

Card is [this Fe-Pi soundcard](https://fe-pi.com/products/fe-pi-audio-z-v2). It is connected to the Pi and I have added `dtoverlay=fe-pi-audio` and `dtoverlay=i2s-mmap` to `config.txt` as the instructions said to. I have also tried setting it as default for PulseAudio but still nothing. I have tried with a mic in both line in and the mic port. I have confirmed the mic is working.

**Comment by hawkeyexp** [comment]
Ok thx - generally the config looks good and devices are mapped.
can you have a look inside the alsamixer on your system if volume is there down or muted for mic/line?
Without the hardware it is always a bit tricky to figure out what fails but i think we could solve it.

**Comment by noahajac** [comment]
I checked out AlsaMixer in dev mode (with OpenAuto). The mic was initially
muted but even after raising it, it still doesn't work. I have tried
multiple configurations as well.

**Comment by hawkeyexp** [comment]
Wait please for pre5 this weekend - after release we will do some more checks.

**Comment by noahajac** [comment]
@hawkeyexp Tried with pre5. With some changes in alsamixer I was able to get mic input working. However a similar issue arrised. It seems like the audio channels would just cut out and I would have to press pause/play on a music app to get it to go again. For example, I have music playing and I go to say a voice command. The command enters fine but I don't hear the response and the music stops, although the display still shows it playing. As it seems like a different issue I attached a new debug log. If you want me to close this one and make a new issue since they are probably different things I understand.

[debug.zip](https://github.com/opencardev/crankshaft/files/2281335/debug.zip)

**Comment by hawkeyexp** [comment]
Thx for the new debug log: in the log it is visible that pulseaudio can't restore a streams after your described behavior. Let's test two things:

Test 1)
- disable for testing the onboard sound - seems to be not needed with your type of card but give it a try cause some other card's didn't like it, too.

Test 2 if 1 fails)
- Add this to /etc/pulse/default.pa

`### Automatically restore the volume of streams and devices`
`load-module module-device-restore`
`load-module module-stream-restore`
`load-module module-card-restore`

**Comment by noahajac** [comment]
Thanks for the help @hawkeyexp.

I have done both test 1 and 2 however the issue unfortunately exists.

To confirm, disabling the onboard sound is done by adding `dtparam=audio=off` to config.txt, correct?

**Comment by hawkeyexp** [comment]
yes that's correct.
Now it's hard and i have no other idea atm. Generally the audio hardware is accessed so the base is correct.
Have you tried it without playing music ?

**Comment by noahajac** [comment]
The same thing happens without any music playing.

It seems like the only audio that works at all is music and even that is finicky.

**Comment by dreamvictim** [comment]
I'm also getting the same audio cutting out as noahajac. I'm using a Hifi berry DAC.

**Comment by hawkeyexp** [comment]
@dreamvictim i'm using a hifiberry dac plus and a usb mic working without problems. The issue is depending on another hardware with builtin mic input by the dac so please open a seperate issue if needed.

**Comment by noahajac** [comment]
I've tested out the card by using CLI (`arecord` and `aplay`) to record me speaking into the mic and then playing it back. That works fine. This seems to be a problem with OpenAuto, should I create an issue [here](https://github.com/f1xpl/openauto/issues)?

**Comment by hawkeyexp** [comment]
no the problem is not openauto - openauto accesses audio hardware via pulseaudio like most of applications.
Possible you can test it out with paplay and parecord. All controls are done via pulseaudio in the system.

**Comment by noahajac** [comment]
Tested out with those commands it works fine as well. Should I try it out by enabling `dtparam=i2s=on`? I believe it uses I2S so should that be enabled?

Also I noticed in the log it says&nbsp;

    crankshaft pulseaudio[2080]: [alsa-sink-Fe-Pi HiFi sgtl5000-0] alsa-sink.c: ALSA woke us 
    up to write new data to the device, but there was actually nothing to write.
    crankshaft pulseaudio[2080]: [alsa-sink-Fe-Pi HiFi sgtl5000-0] alsa-sink.c: Most likely this 
    is a bug in the ALSA driver 'snd_soc_fe_pi_audio'. Please report this issue to the ALSA developers.
    crankshaft pulseaudio[2080]: [alsa-sink-Fe-Pi HiFi sgtl5000-0] alsa-sink.c: We were woken up with POLLOUT set -- however a subsequent snd_pcm_avail() returned 0 or another value <  
    min_avail.

Could this mean something? Could it be a problem with Alsa?

**Comment by hawkeyexp** [comment]
the log errors seems to be normal and is caused by many cards i have seen.

i2s you can try out but i think it will make no change cause your card seems to work.
But with this test it is clear the hardware is generally working and we can nothing other do.
