### ISSUE TITLE
USB Extender for USB mic does not work

### ISSUE THREAD

**Issue by arobe14040** [opencardev/crankshaft#197]
I have a USB mic that I have been using for google assistant which was plugged into the RPi.  I decided to use a USB extender so that I could get the mic closer to my mouth (was previously having a hard time hearing me).

Crankshaft can no longer hear me at all through the mic when using usb extender.  If i plug mic directly into RPi it works fine again.  I also tried plugging a USB stick into the extender with the Pre 4 update on it to see if it was just the mic, and it did not recognize that either.

Any ideas why I can't use a usb extender? Is it a crankshaft issue? or just a RPi issue?

**Comment by hawkeyexp** [comment]
You solved it yourselve...

mic and usb working without extender.
With exender both fails - so the problem is your extender or the used chips not supported.

I recommend don't using exender - they create more probs than solutions.
By a better mic or just check the input volume of the mic.
