### ISSUE TITLE
Support back-up camera

### ISSUE THREAD

**Issue by mburgess00** [opencardev/crankshaft#26]
It would be great if a gpio pin would trigger the input on the camera port on the rpi3.

**Comment by parkerlreed** [comment]
Take a look here https://www.youtube.com/watch?v=Puk_pzMGd7c 

There's an overview in the video and the bottom of the description says he'll get the scripts posted soon.

**Comment by EveAeternam** [comment]
I'm assuming this could be done with a **USB webcam/camera**. Have LXDE open a window showing the camera out with a perspective road layover.

**Comment by hawkeyexp** [comment]
With upcoming builds based on crankshaft-ng branch system will get support to use the rpi cam module as rearcam / dashcam

**Comment by hawkeyexp** [comment]
Released with CS-NG
