### ISSUE TITLE
Implement a dashcam feature

### ISSUE THREAD

**Issue by GerRudi** [opencardev/crankshaft#32]
Definitely not a high priority, but this would also be a great enhancement.

**Comment by ketanpatil3** [comment]
https://www.youtube.com/watch?v=jFXxtxoi_pc
This would work in dev mode.

**Comment by hawkeyexp** [comment]
With upcoming builds based on crankshaft-ng branch system will get support to use the rpi cam module as rearcam / dashcam

**Comment by hawkeyexp** [comment]
Released with CS-NG
