### ISSUE TITLE
USB sound card now distorted on latest version (built in fine)

### ISSUE THREAD

**Issue by a-haan** [opencardev/crankshaft#33]
- What phone do you have? What OS version? Pixel XL 2
- Did you try to enable and run autoapp under X11 dev mode?  no
- Please provide any further information that you might find helpful:

Previous build had no sound problems using the USB sound card, I suspect the sound amplification on this build was for all not just the built in Aux

**Comment by a-haan** [comment]
sound card is https://www.amazon.co.uk/gp/product/B01N905VOY/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1

**Comment by htruong** [comment]
If you're familiar with the command line, can you help me edit a few files to see a "sweet spot?"

**Comment by byransays** [comment]
Same sound card. Fire away with some sweet spot ideas.

**Comment by a-haan** [comment]
the sweet spot for me was the previous version, just reverted back and it's perfect again...

**Comment by htruong** [comment]
New version is less jealous about the volume level. Please help me giving it a try :) 

https://www.reddit.com/r/crankshaft/comments/842r3g/breakthrough_release_crankshaft_alpha_020_and

**Comment by Mearman** [comment]
@htruong does the new release fix the volume and interference issues?

**Comment by Mearman** [comment]
I'll give a go. Thanks

**Comment by a-haan** [comment]
still distorted on the latest build, can you tell me what file I need to edit to adjust the amplification?

**Comment by htruong** [comment]
@a-haan can you try editing `/etc/pulse/default.pa` and remove the line `set-sink-volume 0 52428` or tune it to a smaller number?

**Comment by a-haan** [comment]
Thank you for your help, found a sweet spot at 32428 - music is now loud and crystal clear!

**Comment by poxin13** [comment]
Also had this issue using a Hifiberry. Ended up commenting out the set-sink-volume line and setting volume in alsamixer. Also changed pulseaudio to high-priority & realtime with ffmpeg as the remix per openauto suggestion.
