### ISSUE TITLE
Wireless Android Auto support?

### ISSUE THREAD

**Issue by DGxInfinitY** [opencardev/crankshaft#51]
I was wondering what the ETA on Wireless Android Auto was and if anyone has had a chance to implement it? It would be so nice honestly as I don't really wish to plug in my phone every time I get in the car. Here is the hardware I have as of right now.
- Pixel 2 XL (Android Oreo 8.1.0, March Security Patch)
- Standard Official Raspberry PI Display

**Comment by parkerlreed** [comment]
It is being worked on in OpenAuto/aasdlk (the components Crankshaft uses)

**Comment by htruong** [comment]
This functionality is not mainlined (brought to the official branch) of OpenAuto yet. It is still very hard to use, so even it's working now (with glitchy audio) I feel like this is not yet the prime time to integrate into Crankshaft. I will find a way to latch it into the dev mode of Crankshaft, but I don't yet have a plan to release the feature widely.

**Comment by DGxInfinitY** [comment]
Sure. I get that. I'd love to test the functionality on dev mode for you and provide any aid as needed. I'll be watching for the commit.

**Comment by mbt28** [comment]
I believe this function can work better in pi 3 b+ as it has 5ghz faster wifi. Audio needs latency free transfer, with 2.4ghz version I dont think it is possible to get good results.

**Comment by DGxInfinitY** [comment]
@mbt28 2.4ghz is certainly fast enough for audio transfer. The only limitation of other raspberry pi's are the USB controllers. The Pi2 should be ok but other Raspberry Pi's might experience problems using USB to WiFi adapters because the USB bus controller is so slow.

**Comment by partach** [comment]
Second this enhancement request. The USB-C plug on my HTC U11 is not that solid. It happens frequently that a disconnect happens. This requires fiddling with the plug and paused audio. Connecting via Wifi would really be a blessing... 
And I also will happily test if needed (have a Pi3B+ with offcial 7" touchscreen)

**Comment by DJFliX** [comment]
@DGxInfinitY As of Alpha-1 the [WiFi-functionality](https://github.com/opencardev/crankshaft/wiki/Android-Auto-Wifi) of Android Auto works with Crankshaft. Have you been able to play with it already? I would appreciate it if you could give mee feedback on whether it's working for you. If it is, feel free to close the issue. If it doesn't please let us know and/or share some debug logs so we can investigate.

**Comment by DGxInfinitY** [comment]
@DJFliX So how would I go about enabling and using it? Do I need to setup a hotspot on my phone or what?

**Comment by hawkeyexp** [comment]
Have a look to the wiki - the wireless part is updated and explains both use cases

**Comment by rppgen** [comment]
Anyone tried Android auto wireless on rasberry?

**Comment by DJFliX** [comment]
> Anyone tried Android auto wireless on rasberry?

Yes. Please read [this](https://github.com/opencardev/crankshaft/wiki/Android-Auto-Wifi).

**Comment by rppgen** [comment]
Thanks, is there a video out there too?
Will help a lot.

**Comment by toufou54** [comment]
Work fine for me too, check the wiki (why this issue is not closed ?)

**Comment by parkerlreed** [comment]
Because it still requires dev options. The intent would be to have the actual wireless pairing mode be available.

**Comment by alextytan** [comment]
works fine for me too. i have a oneplus3t. i have only added wifi_country, my mobile's hotspot ssid and pass. and i have started head unit server on mobile's android auto

**Comment by matt2005** [comment]
Resolved since alpha1
