### ISSUE TITLE
Package as Debian packages

### ISSUE THREAD

**Issue by htruong** [opencardev/crankshaft#6]
It would be nice to be able to distribute OpenAuto/Crankshaft as a Debian package. Figure out how.

**Comment by parkerlreed** [comment]
Do you have generic building instructions for `aasdk`/`openauto` for Linux? I've been attempting on my regular computer (had to manually copy the `aadsk` include/ directory to my /usr/include) and got `openauto` to almost compile but ended up with a bunch of undefined references when linking `autoapp`.

**Comment by parkerlreed** [comment]
Success! 
![screenshot_20180226_173049](https://user-images.githubusercontent.com/841440/36699527-e87ec07c-1b1a-11e8-921d-24997469a398.png)

**Comment by hawkeyexp** [comment]
I think should be closed cause deb package is not the way to create a whole system :-)
