### ISSUE TITLE
System periodically signals poweroff in DEV terminal mode

### ISSUE THREAD

**Issue by chaoman** [opencardev/crankshaft#80]
- What phone do you have? What OS version? HTC 10 running Android 8.0.0
- Did you try to enable and run autoapp under X11 dev mode?  Follow this: https://github.com/htruong/crankshaft/wiki/Crankshaft-dev-mode
Yes, this problem happens in the dev mode
- Please provide any further information that you might find helpful.

I just download the latest build Crankshaft Openauto 0.2.3 2018-04-18 and try to change the audio setting in the dev mode terminal screen. However, the system keeps signaling the following message periodically like every minute. Below are terminal messages.

 ```
pi@crankshaft:~ $
Broadcast message from root@crankshaft (Thu 2016-11-03 17:21:45 UTC):

The system is going down for poweroff at Thu 2016-11-03 17:31:45 UTC!


Broadcast message from root@crankshaft (Thu 2016-11-03 17:22:45 UTC):

The system is going down for poweroff at Thu 2016-11-03 17:31:45 UTC!


Broadcast message from root@crankshaft (Thu 2016-11-03 17:23:45 UTC):

The system is going down for poweroff at Thu 2016-11-03 17:31:45 UTC!


Broadcast message from root@crankshaft (Thu 2016-11-03 17:24:45 UTC):

The system is going down for poweroff at Thu 2016-11-03 17:31:45 UTC!


Broadcast message from root@crankshaft (Thu 2016-11-03 17:25:45 UTC):

The system is going down for poweroff at Thu 2016-11-03 17:31:45 UTC!


Broadcast message from root@crankshaft (Thu 2016-11-03 17:26:45 UTC):

The system is going down for poweroff at Thu 2016-11-03 17:31:45 UTC!


Broadcast message from root@crankshaft (Thu 2016-11-03 17:27:45 UTC):

The system is going down for poweroff at Thu 2016-11-03 17:31:45 UTC!


Broadcast message from root@crankshaft (Thu 2016-11-03 17:28:45 UTC):

The system is going down for poweroff at Thu 2016-11-03 17:31:45 UTC!
```

**Comment by Maju3** [comment]
I think this is because the "No connection" power off feature.
By default it is setted to 15 mins.
That means when you have NO phone connected the PI shuts down after 15 mins.

But you can set it to "0" to disable it.

Edit the /boot/crankshaft/crankshaft_env.sh and set that NO_CONNECTION_POWEROFF_MINS to 0, and it won't auto-shutoff.

**Comment by htruong** [comment]
I see. This will be fixed. For now do the poweroff workaround or type `shutdown -c`.
