### ISSUE TITLE
audio problem

### ISSUE THREAD

**Issue by sastreae** [opencardev/crankshaft#97]
when you turn on the rp3 it makes low blows in the speakers, and then small blows every time the yellow light is turned on in the rp3. 
any suggestions???
thanks for this project

**Comment by Elmardus** [comment]
Are you using the default speaker output of the pi, or an external USB soundcard? The Pi's DAC is pretty bad, so I recommend using an external USB audiocard, they are very cheap on Aliexpress/Ebay.

The blows you hear are probably caused by interference from the power supply, since the current usage spikes when the pi is writing to the SD card (when the led flashes).

**Comment by htruong** [comment]
Do you mind testing with a more controlled environment, such as taking your setup to your home theater system/isolated speakers, and a nice power supply. If you hear the hums there too, it just means that your ears are sensitive to the DAC that the Pi has. Use a high quality DAC such a the Hifi Berry/ Google AIY/ etc. might help.

**Comment by sastreae** [comment]
hello, sorry for the delay. yes, use the jack of the raspberry and also use the external usb card sentey. With this card the problem is another, but compatibility.
I'm going to try it inside the house with the home theater. thanks for answering, I will bring you the news

**Comment by internix14** [comment]
same problems here, i have been trying for so many hours, i tried 2 DAC's but the dac i bought is noname brand, 5 diffrent power supply's also changed all cables multiple times with and without touchscreen, heck even with HDMI. setting the pi up for the dacs etc. nothing works. i also tried at home with good power supply.. but the problem has allways been there, everytime the pi's CPU is working it is doing that noise. my plan is now to buy the google soundboard.. but first i have recently bought a pi 3 B+, i will try with that first. the problem for me happend about 8 builds ago btw.
